nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-2.4.0.cjs

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependencies:
      typescript: "*"
  "graphql-config@*":
    peerDependencies:
      typescript: "*"
  "eslint-plugin-graphql@*":
    peerDependencies:
      typescript: "*"
  "gatsby@*":
    peerDependencies:
      typescript: "*"
  "gatsby-plugin-typescript@*":
    peerDependencies:
      gatsby: "*"
  "gatsby-plugin-preact@*":
    peerDependencies:
      webpack: "*"