// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Layout(Props) {
  var children = Props.children;
  return React.createElement("main", {
              className: "max-w-3xl"
            }, children);
}

var make = Layout;

export {
  make ,
  
}
/* react Not a pure module */
